app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/




Route::resource('/', 'LinkController');
Route::resource('user', 'UserController');
Route::resource('link', 'LinkController');

//restringiendo rutas con el middleware auth
Route::group(['middleware' => 'auth'], function() {
	Route::resource('category', 'CategoryController');
	Route::resource('user', 'UserController');
	Route::resource('link', 'LinkController');
});

//auth
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

app/Category.php
<?php

namespace Linko;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'category';

    protected $fillable = ['name'];

    //para deshabilitar los campos de creado y editado.
    public $timestamps = false;

    public function links()
	{
	    return $this->hasMany('Linko\Link');
	}
}

app/Http/Controllers/CategoryController.php
<?php

namespace Linko\Http\Controllers;

use Illuminate\Http\Request;

use Linko\Http\Requests;
use Linko\Http\Controllers\Controller;
use Linko\Category;
use Linko\Link;


class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = \Linko\Category::All();
        return view('category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        \Linko\Category::create([
            'name' => $request['name']
        ]);

        return redirect('category')->with('message', 'store');
        

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        

        //buscar categoría por id
        $categories_find = Category::findOrFail($id);

        $links = \DB::table('links')->where('category_id', '=', $id)->get();
        //dd($links);

        return view('category.show', compact('categories_find', 'links', 'categories'));
    }


    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return view('category.edit', compact('category'));
    }

    public function update(Request $request, $id)
    {
        $category = Category::find($id);
        $category->fill($request->all());
        $category->save();

        return redirect('category')->with('message', 'update');
    }


    public function destroy($id)
    {
        //
    }
}

resources/views/category/create.blade.php
@extends('layouts.master')

@section('content')
	<div class="container">
		{!!Form::open(['route' => 'category.store', 'method' => 'POST'])!!}
			@include('category.partials.fields')
		{!!Form::submit('Crear', ['class' => 'btn btn-info'])!!}
	</div>
@stop

resources/views/category/edit.blade.php
@extends('layouts.master')

@section('content')
	<div class="container">
		{!!Form::model($category, ['route' => ['category.update', $category->id], 'method' => 'PUT'])!!}
			@include('category.partials.fields')
		{!!Form::submit('Actualizar', ['class' => 'btn btn-info'])!!}
	</div>
@stop

resources/views/category/index.blade.php
@extends('layouts.master')

<?php $message = Session::get('message')?>

@section('content')

	<div class="container">
		@if($message == 'store')
			<div class="alert alert-success">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		  		<strong>Success!</strong> La categoría se creó exitosamente.
			</div>
		@endif
		@if($message == 'update')
			<div class="alert alert-success">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		  		<strong>La categoría se actualizó exitosamente.</strong>
			</div>
		@endif
		<div class="row">
			<div class="col-xs-3">
				<h3>Categorías actuales</h3>
			</div>
			<div class="col-xs-6">
				<a href="category/create" class="btn btn-info btn-xs btn-cat">Crear categoría</a>
			</div>
		</div>
		<hr />
		<div class="row">
			@foreach($categories as $category)
				<div class="panel panel-default col-xs-3 item_category">
					<br>
					<div class="row">
						<div class="col-xs-10">
							{{$category->name}}	
						</div>
						<div class="col-xs-2">
							{!!link_to_route('category.edit',$title ='', $parameter = $category->id, $attribute = ['class' => 'glyphicon glyphicon-pencil'])!!}		
						</div>
					</div>
				</div>
			@endforeach
		</div>
	</div>
@stop

resources/views/category/show.blade.php
@extends('layouts.master')

@section('content')
	<div class="container">
		<dir class="row">
			<h2>{{$categories_find->name}}</h2>	
		</dir>
		<hr />
		<div class="row">
			@foreach($links as $link)
			<div class="col-xs-4">
				<div class="panel panel-primary item">
					<div class="panel-heading"><p><strong>{{$link->title}}</strong></p></div>
					<div class="panel-body">
						<div class="row">
							<div class="col-xs-10">
								<p>{{$link->description}}</p> 
							</div>
							<div class="col-xs-1">
								<a href="{{$link->url}}" target="_blank"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
							</div>
						</div>
					</div>
					<div class="panel-footer">
						<div class="row">
							<div class="col-xs-4">
								{!!link_to_route('link.edit',$title ='', $parameter = $link->id, $attribute = ['class' => 'glyphicon glyphicon-pencil'])!!}
							</div>
							<div class="col-xs-8">
								<small><strong>Creado el: {{$link->created_at}}</strong></small>
							</div>
						</div>
					</div>
				</div>
			</div>
			@endforeach
		</div>
	</div>
@stop