app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/




Route::resource('/', 'LinkController');
Route::resource('user', 'UserController');
Route::resource('link', 'LinkController');

//restringiendo rutas con el middleware auth
Route::group(['middleware' => 'auth'], function() {
	Route::resource('category', 'CategoryController');
	Route::resource('user', 'UserController');
	Route::resource('link', 'LinkController');
});

//auth
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Linko - Ordena tus favoritos como quieras</title>

    <!-- Bootstrap Core CSS -->
    {!!Html::style('css/bootstrap.min.css')!!}
    {!!Html::style('css/style.css')!!}
    

    <!-- Custom CSS -->
    <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="row">
            <!-- Brand and toggle get grouped for better mobile display -->
                <div class="col-xs-6">
                    <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Linko</a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="../user">Perfil</a>
                        </li>
                        <li>
                            <a href="../link/create">Guardar Url</a>
                        </li>
                        <li>
                            @if(Auth::user())
                                <a href="../auth/logout">Salir</a>
                            @endif                        
                        </li>
                    </ul>
                </div>
                </div>
                <div class="col-xs-6 user-name text-center">
                    <h4>
                        <p class="user-p">
                            @if( Auth::user() )
                                {{Auth::user()->name}}
                            @else
                                <a href="../auth/login">Login</a>
                            @endif
                        </p>
                    </h4>
                </div>
            <!-- /.navbar-collapse -->
            </div>
        </div>
        <!-- /.container -->
    </nav>
    <div class="container">
        <div class="row">
        <div class="col-xs-1">Categorías: </div>
        <div class="col-xs-11">
            <div class="btn-group btn-group-xs" role="group" aria-label="Extra-small button group">
                @foreach($categories as $category)
                    {!!link_to_route('category.show',$title = $category->name, $parameter = $category->id, $attribute = ['class' => 'btn btn-default'])!!}  
                @endforeach
            </div>
        </div>
        </div>
    </div>
    <br />
    <!-- Page Content -->

        @yield('content')
        <!-- /.row -->


  
    <!-- /.container -->

    <!-- jQuery Version 1.11.1 -->
    {!!Html::script('js/jquery.js')!!}

    <!-- Bootstrap Core JavaScript -->
    {!!Html::script('js/bootstrap.min.js')!!}
    {!!Html::script('js/script.js')!!}

</body>

</html>